// This file is generated by Fumadocs
export const map = [
  {
    type: 'page',
    url: '/docs',
    file: () => import('../content/docs/index.mdx'),
    data: {
      title: 'Getting Started',
      description: 'Learn how to integrate React LLM into your project in 30 seconds'
    }
  },
  {
    type: 'page', 
    url: '/docs/installation/script-tag',
    file: () => import('../content/docs/installation/script-tag.mdx'),
    data: {
      title: 'Script Tag Installation',
      description: 'Add React LLM to any website with a simple script tag'
    }
  },
  {
    type: 'page',
    url: '/docs/installation/npm-package', 
    file: () => import('../content/docs/installation/npm-package.mdx'),
    data: {
      title: 'NPM Package Installation',
      description: 'Install React LLM as an npm package for better integration and TypeScript support'
    }
  }
] as const;